name: 'placeholders_pipeline'
version: '1.0.0'

profile: 'placeholders_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  placeholders_pipeline:
    staging:
      +schema: STAGING
      +materialized: view
    mart:
      +schema: MART
      +materialized: table