version: 2

sources:
  - name: raw
    database: JSONPLACEHOLDER_PIPELINE_DB
    schema: RAW
    tables:
      - name: jsonplaceholder_raw
        identifier: JSONPLACEHOLDER_RAW
        description: "Raw JSON data loaded from AWS S3 into Snowflake."