-- ============================================================
-- Snowflake setup for AWS S3 API Ingestion Pipeline
-- ============================================================

CREATE DATABASE IF NOT EXISTS JSONPLACEHOLDER_PIPELINE_DB;

CREATE SCHEMA IF NOT EXISTS JSONPLACEHOLDER_PIPELINE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS JSONPLACEHOLDER_PIPELINE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS JSONPLACEHOLDER_PIPELINE_DB.MART;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL',
    AUTO_SUSPEND = 60,
    AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE JSONPLACEHOLDER_PIPELINE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE TABLE JSONPLACEHOLDER_RAW (
    raw_data VARIANT,
    source_file STRING,
    loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STAGE S3_JSONPLACEHOLDER_STAGE
    URL = 's3://<BUCKET_NAME>/marketing_data/raw/jsonplaceholder/'
    CREDENTIALS = (
        AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>',
        AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
    )
    FILE_FORMAT = JSON_FORMAT;